context("Numeric returns")
library(geodiv)
data(normforest)

test_that("incorrect inputs return errors", {
  expect_error(aacf('a'), 'x must be a raster.')
  expect_error(scl('a'), 'x must be a raster.')
  expect_error(str('a'), 'x must be a raster.')
  expect_error(sa('a'), 'x must be a raster.')
  expect_error(sq('a'), 'x must be a raster.')
  expect_error(ssk('a'), 'x must be a raster.')
  expect_error(sku('a'), 'x must be a raster.')
  expect_error(sv('a'), 'x must be a raster.')
  expect_error(sph('a'), 'x must be a raster.')
  expect_error(smean('a'), 'x must be a raster.')
  expect_error(scl(normforest, threshold = -0.1, plot = FALSE), 'threshold values cannot be less than 0.')
  expect_error(scl(normforest, threshold = 'a', plot = FALSE), 'threshold must be numeric.')
  expect_error(scl(normforest, plot = 'a'), 'plot argument must be TRUE/FALSE.')
  expect_error(ssk(normforest, adj = 'a'), 'adj argument must be TRUE/FALSE.')
  expect_error(sku(normforest, excess = 'a'), 'excess argument must be TRUE/FALSE.')
  expect_error(str(normforest, threshold = -0.1), 'threshold values cannot be less than 0.')
  expect_error(str(normforest, threshold = 'a'), 'threshold must be numeric.')
})
